import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 30, 300)
wave1 = np.sin(x / 4)
wave2 = np.cos(x / 4)
fig, (plot1, plot2) = plt.subplots(2, 1, figsize=(10, 8))
plot1.plot(x, wave1, label='sin(x/4)', color='blue', linestyle='-')
plot1.set_title('Sine Function (x/4)')
plot1.set_xlabel('X values')
plot1.set_ylabel('sin(x/4)')
plot1.grid(True)
plot1.legend(loc='upper right')
plot1.set_xticks(np.arange(0, 31, 3))
plot1.set_yticks(np.arange(-1, 1.5, 0.5))
plot1.set_xticklabels([f'{i}' for i in range(0, 31, 3)])
plot1.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
plot1.annotate('Peak', xy=(2*np.pi, 1), xytext=(2*np.pi + 4, 0.8), arrowprops=dict(facecolor='black', shrink=0.05))
plot2.plot(x, wave2, label='cos(x/4)', color='red', linestyle='--')
plot2.set_title('Cosine Function (x/4)')
plot2.set_xlabel('X values')
plot2.set_ylabel('cos(x/4)')
plot2.grid(True)
plot2.legend(loc='upper right')
plot2.set_xticks(np.arange(0, 31, 3))
plot2.set_yticks(np.arange(-1, 1.5, 0.5))
plot2.set_xticklabels([f'{i}' for i in range(0, 31, 3)])
plot2.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
plot2.annotate('Valley', xy=(4*np.pi, -1), xytext=(4*np.pi + 4, -0.8), arrowprops=dict(facecolor='black', shrink=0.05))
plt.tight_layout()
plt.savefig('wave_plot.png')
plt.show()
