import matplotlib.pyplot as plt
import numpy as np
x_values = np.linspace(0, 20, 200)
data1 = np.sin(x_values / 2)
data2 = np.cos(x_values / 2)
fig, (axis1, axis2) = plt.subplots(2, 1, figsize=(10, 8))
axis1.plot(x_values, data1, label='sin(x/2)', color='blue', linestyle='-')
axis1.set_title('Sine Wave (x/2)')
axis1.set_xlabel('X values')
axis1.set_ylabel('sin(x/2)')
axis1.grid(True)
axis1.legend(loc='upper right')
axis1.set_xticks(np.arange(0, 21, 1))
axis1.set_yticks(np.arange(-1, 1.5, 0.5))
axis1.set_xticklabels([f'{i}' for i in range(21)])
axis1.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
axis1.annotate('Peak', xy=(np.pi, 1), xytext=(np.pi + 2, 0.8), arrowprops=dict(facecolor='black', shrink=0.05))
axis2.plot(x_values, data2, label='cos(x/2)', color='red', linestyle='--')
axis2.set_title('Cosine Wave (x/2)')
axis2.set_xlabel('X values')
axis2.set_ylabel('cos(x/2)')
axis2.grid(True)
axis2.legend(loc='upper right')
axis2.set_xticks(np.arange(0, 21, 1))
axis2.set_yticks(np.arange(-1, 1.5, 0.5))
axis2.set_xticklabels([f'{i}' for i in range(21)])
axis2.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
axis2.annotate('Valley', xy=(2 * np.pi, -1), xytext=(2 * np.pi + 2, -0.8), arrowprops=dict(facecolor='black', shrink=0.05))
plt.tight_layout()
plt.savefig('trig_wave_plot.png')
plt.show()
